/* Service worker — offline app shell for the Neill Data suite (§1.8).
 *
 * Strategy (v2 — fixes the frozen-deploy bug; v5 — fixes the stale tile list):
 *   - navigations (HTML), index.html and apps.json: network-first with
 *     {cache:'no-cache'} (revalidates past the 10-min HTTP cache), cache
 *     fallback when offline. v4 served apps.json stale-while-revalidate, so
 *     the first open after a deploy showed the old app list (new tiles missing
 *     until a second load). apps.json is generated by hub/build-apps.cjs on
 *     every push, so it must never lag a deploy.
 *   - same-origin assets (js/css/img): stale-while-revalidate — served from
 *     cache instantly, refreshed in the background, so a deploy lands on
 *     the next load instead of never
 *   - Google APIs (Sheets/Drive/Maps/OAuth): network-only, never cached —
 *     nd-queue owns write resilience, not this cache
 *   - install precaches with {cache:'reload'} to bypass the HTTP cache
 *     (a stale CDN copy must not get frozen into the SW cache)
 */

const CACHE_VERSION = 'hub-v11'; // v11: Assets 1.2.0 visual library (1234567890/visual-catalog.json); v10: hub 0.7.1 — Recent jobs quick launch (shared/nd-recent-jobs.js precached); v9: hub 0.6.5 — hub icons back to the teal Suite hub icon (favicon, apple-touch, manifest, maskable); v8: hub 0.6.4 — Neill Data (ND) suite logo: favicon, apple-touch, manifest + maskable icons; v7: hub 0.6.3 — header clears the sync badge; v6: hub 0.6.2 — opaque PNG home-screen icons (icon-180 apple-touch-icon); v5: apps.json + HTML network-first
const SHELL_ASSETS = [
  "./",
  "./index.html",
  "./manifest.json",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-192.png",
  "./icons/maskable-512.png",
  "./apps.json",
  "./favicon.svg?v=0.6.5",
  "../shared/nd-core.css",
  "./styles.css?v=0.7.1",
  "../shared/nd-match.js",
  "../shared/nd-cache.js",
  "../shared/nd-ui.js",
  "../shared/nd-recent-jobs.js?v=1",
  "../shared/nd-pwa.js",
  "./app.js?v=0.7.1"
];

const IS_API_HOST = (url) =>
  /\b(googleapis\.com|accounts\.google\.com|google\.com\/macros)\b/.test(url);

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_VERSION)
      .then((cache) => Promise.all(
        SHELL_ASSETS.map((u) =>
          cache.add(new Request(u, { cache: 'reload' })).catch(() => null)
        )
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;    // writes belong to nd-queue, never the cache
  if (IS_API_HOST(req.url)) return;    // Sheets/Drive/Maps/OAuth always hit the network
  if (new URL(req.url).origin !== self.location.origin) return; // CDN etc: browser default

  const path = new URL(req.url).pathname;
  const fresh = req.mode === 'navigate' || /\/hub\/(index\.html|apps\.json)?$/.test(path);
  if (fresh) {
    // network-first: fresh HTML / app list when online, cached copy when offline
    event.respondWith(
      fetch(req, { cache: 'no-cache' })   // revalidate: never trust the 10-min HTTP cache here
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE_VERSION).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req, { ignoreSearch: true })
          .then((c) => c || caches.match(req.mode === 'navigate' ? './index.html' : req)))
    );
    return;
  }

  // stale-while-revalidate for everything else same-origin
  event.respondWith(
    caches.open(CACHE_VERSION).then((cache) =>
      cache.match(req).then((cached) => {
        const refresh = fetch(req)
          .then((res) => {
            if (res.ok) cache.put(req, res.clone());
            return res;
          })
          .catch(() => cached);
        return cached || refresh;
      })
    )
  );
});
